<?php
/**
 * @copyright   Copyright (C) 2022 Arturo Luna
 * @license     [AGPLv3](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License)
*/
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'itop-al-airconditioner/1.1.0',
	array(
		// Identification
		//
		'label' => 'Air conditioner',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'itop-config-mgmt/2.6.0'//,
//			'itop-datacenter-mgmt/2.6.0',
//			'itop-change-mgmt/2.6.0',
//			'itop-endusers-devices/2.6.0'  //reuqueridos para agregar al menu https://www.itophub.io/wiki/page?id=2_5_0%3Acustomization%3Aadd-class-sample#final_customization_module
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'model.itop-al-airconditioner.php' // Contains the PHP code generated by the "compilation" of datamodel.itop-al-airconditioner.xml
		),
		'webservice' => array(
			
		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),
		
		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);


?>
